name: Docker Build and Push

on:
  workflow_dispatch:
    inputs:
      DOCKER_IMAGE_VERSION:
        description: 'Docker Image Version'
        required: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./virtual
          push: true
          tags: |
            yakirbartech/pipemasterci:${{ github.event.inputs.DOCKER_IMAGE_VERSION }}

      - name: Logout from Docker Hub
        run: docker logout

  pull-and-run:
    needs: build-and-push
    runs-on: self-hosted

    steps:
      - name: Pull and run Docker image
        run: sudo docker run -d --name Test -p 8001:8001 -e PORT=8001 -e CONTENT="&lt;h1&gt;HEYd&lt;/h1&gt;&lt;h2&gt;HEY world&lt;/h2&gt;" yakirbartech/pipemasterci:${{ github.event.inputs.DOCKER_IMAGE_VERSION }}
