name: Docker Build and Push

on:
  workflow_dispatch:
    inputs:
      DOCKER_CONTAINER_PORT:
        description: "Docker Container Port"
        required: true
      DOCKER_CONTAINER_CONTENT:
        description: "Docker Container Content"
        required: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./virtual
          push: true
          tags: |
            yakirbartech/pipemasterci:1.0.7

      - name: Logout from Docker Hub
        run: docker logout

  pull-and-run:
    needs: build-and-push
    runs-on: self-hosted

    steps:
      - name: Pull and run Docker image
        run: |
          sudo docker run -d --name Test123 \
            -p ${{ github.event.inputs.DOCKER_CONTAINER_PORT }}:${{ github.event.inputs.DOCKER_CONTAINER_PORT }} \
            -e PORT=${{ github.event.inputs.DOCKER_CONTAINER_PORT }} \
            -e CONTENT=${{ github.event.inputs.DOCKER_CONTAINER_CONTENT }}
            yakirbartech/pipemasterci:1.0.7
